# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

title                    : "Tang Kai | Academic Homepage"
description              : "Remote sensing, agricultural intelligence, change detection, data fusion, and GeoAI"
repository               : "tangkai-RS/tangkai-RS.github.io"
url                      : "https://tangkai-rs.github.io"
baseurl                  : ""
# google_scholar_stats_use_cdn : true

# google analytics
# google_analytics_id    :

# SEO Related
google_site_verification :
bing_site_verification   :
baidu_site_verification  :

# Site Author
author:
  name             : "Tang Kai"
  name_cn          : "(唐凯)"
  avatar           : "images/profile-photo.jpg"
  bio              : "Ph.D. Candidate, Beijing Normal University"
  location         : "Beijing, China"
  employer         :
  pubmed           :
  googlescholar    : "https://scholar.google.com.hk/citations?user=cNylwdwAAAAJ&hl=zh-CN"
  email            : "tangkai@mail.bnu.edu.cn"
  researchgate     : "https://www.researchgate.net/profile/Kai-Tang-31"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "tangkai-RS"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         :
  dblp             :
  orcid            : "https://orcid.org/0000-0001-6100-4441"
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :

include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - .github
  - .jekyll-cache
  - .vscode
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - debug.log
  - Gemfile
  - Gruntfile.js
  - jekyll-preview.err.log
  - jekyll-preview.log
  - LICENSE
  - LOCAL_SETUP.md
  - README
  - Rakefile
  - run_server.sh
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Shanghai

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
